#name: Dart
#
#on:
#  push:
#    branches: [ "master" ]
#    tags:
#      - 'v*'
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#
#    steps:
#      - uses: actions/checkout@v3
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.7.7'
#          channel: 'stable'
#
#      - name: Push to Releases
#        uses: ncipollo/release-action@v1.13.0
#        with:
##           artifacts: "build/app/outputs/apk/debug/*,build/ios/iphoneos/app.ipa"
#           artifact: "build/app/outputs/flutter-apk/app-release.apk"
#           tag: v1.0.${{ github.run_number }}
##           token: ${{ secrets.TOKEN }}



on:
  push:
    branches:
      - master

name: Build My Apps

jobs:
  build:
    name: Build and Release new apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build apk --release --split-per-abi

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v0.0.1
          token: ${{ secrets.TOKEN }}








